name: Release Rust App

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


env:
  CARGO_TERM_COLOR: always
  APP_NAME: "CPUsage"

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build and Bundle application
        run: cargo test --verbose && cargo bundle --release

      - name: Package .app bundle
        run: |
          ditto -c -k --sequesterRsrc --keepParent "target/release/bundle/osx/${{ env.APP_NAME }}.app" "target/release/${{ env.APP_NAME }}.zip"

      - name: Semantic Release and Upload
        uses: codfish/semantic-release-action@v4
        with:
          upload_assets: "target/release/${{ env.APP_NAME }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
